
name: GitGuardian scan

on:
  workflow_dispatch:

jobs:
  scanning:
    runs-on: ubuntu-latest
    name: GitGuardian scan

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install ggshield
        run: pip install --upgrade ggshield

      - name: API Status
        run: ggshield api-status
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      - name: GitGuardian CI scan
        run: ggshield secret scan ci
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      - name: GitGuardian path scan
        run: ggshield secret scan path .

      - name: GitGuardian full history scan
        run: ggshield secret scan repo .
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
